import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { TestVariables } from '../../TestVariables.js';
import { CadDocument } from '../../../src/CadDocument.js';
import { ACadVersion } from '../../../src/ACadVersion.js';
import { XYZ } from '../../../src/Math/XYZ.js';
import { Point } from '../../../src/Entities/Point.js';
import { Line } from '../../../src/Entities/Line.js';
import { DwgWriter } from '../../../src/IO/DWG/DwgWriter.js';

/**
 * Compare DWG files generated by TS ACadSharp with those from C# ACadSharp.
 *
 * C# reference files are generated by: reference/csharp-ref/DwgRefGen
 * Run: dotnet run -- <output>
 */

const csharpRefDir = path.join(TestVariables.outputSamplesFolder, 'csharp-ref-dwg');
const tsOutDir = path.join(TestVariables.outputSamplesFolder, 'generated', 'simple');

const writableVersions: { version: ACadVersion; name: string }[] = [
  { version: ACadVersion.AC1014, name: 'AC1014' },
  { version: ACadVersion.AC1015, name: 'AC1015' },
  { version: ACadVersion.AC1018, name: 'AC1018' },
  { version: ACadVersion.AC1024, name: 'AC1024' },
  { version: ACadVersion.AC1027, name: 'AC1027' },
  { version: ACadVersion.AC1032, name: 'AC1032' },
];

/** Parse AC15 (AC1014/AC1015) file header records */
function parseAC15Records(bytes: Uint8Array): { name: string; seeker: number; size: number }[] {
  const names: Record<number, string> = {
    0: 'Header', 1: 'Classes', 2: 'Handles', 3: 'ObjFreeSpace', 4: 'Template', 5: 'AuxHeader',
  };
  const records: { name: string; seeker: number; size: number }[] = [];
  let offset = 25; // after preamble
  for (let r = 0; r < 6; r++) {
    const num = bytes[offset];
    const view = new DataView(bytes.buffer, bytes.byteOffset + offset + 1, 8);
    const seeker = view.getInt32(0, true);
    const size = view.getInt32(4, true);
    records.push({ name: names[num] ?? `Record_${num}`, seeker, size });
    offset += 9;
  }
  return records;
}

function createSimpleDoc(version: ACadVersion): CadDocument {
  const doc = new CadDocument();
  doc.header.version = version;
  const p = new Point(new XYZ(10, 5, 0));
  const l = new Line(new XYZ(0, 0, 0), new XYZ(50, 30, 0));
  doc.entities.add(p);
  doc.entities.add(l);
  return doc;
}

function writeDwg(doc: CadDocument): Uint8Array {
  const buffer = new ArrayBuffer(4 * 1024 * 1024);
  const writer = new DwgWriter(buffer, doc);
  writer.write();
  return new Uint8Array(buffer, 0, writer.bytesWritten);
}

describe('DwgCSharpComparison', () => {
  // Skip if C# reference files not generated
  const hasCSharpRef = fs.existsSync(csharpRefDir) &&
    fs.readdirSync(csharpRefDir).some(f => f.endsWith('.dwg'));

  describe.skipIf(!hasCSharpRef)('compare TS vs C# output', () => {
    for (const { version, name } of writableVersions) {
      it(`${name}: section sizes within 20% of C#`, () => {
        // Generate TS output
        const doc = createSimpleDoc(version);
        const tsBytes = writeDwg(doc);

        // Read C# reference
        const csPath = path.join(csharpRefDir, `simple_${name}.dwg`);
        const csBytes = new Uint8Array(fs.readFileSync(csPath));

        // Version string should match
        const tsVersion = new TextDecoder().decode(tsBytes.slice(0, 6));
        const csVersion = new TextDecoder().decode(csBytes.slice(0, 6));
        expect(tsVersion).toBe(csVersion);

        // File size should be within 30% of C# (allowing for Object section differences)
        const sizeRatio = tsBytes.length / csBytes.length;
        expect(sizeRatio).toBeGreaterThan(0.7);
        expect(sizeRatio).toBeLessThan(1.3);

        // For AC15 format, compare section sizes
        if (version <= ACadVersion.AC1015) {
          const tsRecords = parseAC15Records(tsBytes);
          const csRecords = parseAC15Records(csBytes);

          for (let i = 0; i < tsRecords.length; i++) {
            const ts = tsRecords[i];
            const cs = csRecords[i];
            expect(ts.name).toBe(cs.name);

            // Classes and Template should match exactly
            if (ts.name === 'Classes' || ts.name === 'Template' || ts.name === 'AuxHeader') {
              expect(ts.size).toBe(cs.size);
            }
          }
        }

        // Log comparison for debugging
        console.log(`${name}: TS=${tsBytes.length} C#=${csBytes.length} ratio=${(sizeRatio * 100).toFixed(0)}%`);
      });
    }
  });
});
