import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { TestVariables } from '../../TestVariables.js';
import { readFileAsArrayBuffer } from '../../testHelpers.js';
import { CadDocument } from '../../../src/CadDocument.js';
import { ACadVersion } from '../../../src/ACadVersion.js';
import { XYZ } from '../../../src/Math/XYZ.js';
import { Point } from '../../../src/Entities/Point.js';
import { Line } from '../../../src/Entities/Line.js';
import { Circle } from '../../../src/Entities/Circle.js';
import { Arc } from '../../../src/Entities/Arc.js';
import { DwgWriter } from '../../../src/IO/DWG/DwgWriter.js';
import { DwgReader } from '../../../src/IO/DWG/DwgReader.js';

const writableVersions = [
  ACadVersion.AC1014,
  ACadVersion.AC1015,
  ACadVersion.AC1018,
  ACadVersion.AC1024,
  ACadVersion.AC1027,
  ACadVersion.AC1032,
];

function writeDocumentToFile(doc: CadDocument, outPath: string): void {
  const buffer = new ArrayBuffer(4 * 1024 * 1024);
  const writer = new DwgWriter(buffer, doc);
  writer.write();
  fs.writeFileSync(outPath, new Uint8Array(buffer, 0, writer.bytesWritten));
}

describe('DwgFileCreationTests', () => {
  it('CreateSimpleDwgFiles', () => {
    const outDir = path.join(TestVariables.outputSamplesFolder, 'generated', 'simple');
    fs.mkdirSync(outDir, { recursive: true });

    for (const version of writableVersions) {
      const doc = new CadDocument();
      doc.header.version = version;

      const p = new Point(new XYZ(10, 5, 0));
      const l = new Line(new XYZ(0, 0, 0), new XYZ(50, 30, 0));

      doc.entities.add(p);
      doc.entities.add(l);

      const outPath = path.join(outDir, `simple_${ACadVersion[version]}.dwg`);
      writeDocumentToFile(doc, outPath);

      expect(fs.existsSync(outPath)).toBe(true);
      expect(fs.statSync(outPath).size).toBeGreaterThan(0);

      const readBack = new DwgReader(readFileAsArrayBuffer(outPath));
      const parsed = readBack.read();
      expect(parsed).not.toBeNull();
    }
  });

  it('CreateComplexDwgFiles', () => {
    const outDir = path.join(TestVariables.outputSamplesFolder, 'generated', 'complex');
    fs.mkdirSync(outDir, { recursive: true });

    for (const version of writableVersions) {
      const doc = new CadDocument();
      doc.header.version = version;
      doc.summaryInfo = {
        title: `Complex ${ACadVersion[version]}`,
        subject: 'Generated by DwgFileCreationTests',
        author: 'ACadSharp.Tests',
        keywords: 'complex,dwg,generated',
        comments: 'Auto-generated complex DWG output',
      } as any;

      const extraPoint = new Point(new XYZ(100, 100, 0));
      const extraLine = new Line(new XYZ(100, 100, 0), new XYZ(140, 115, 0));
      const extraCircle = new Circle();
      extraCircle.center = new XYZ(25, 25, 0);
      extraCircle.radius = 6;

      const extraArc = new Arc(new XYZ(40, 40, 0), 10, 0.25, 2.9);

      if (doc.entities && typeof doc.entities.add === 'function') {
        doc.entities.add(extraPoint);
        doc.entities.add(extraLine);
        doc.entities.add(extraCircle);
        doc.entities.add(extraArc);
        for (let i = 0; i < 25; i++) {
          doc.entities.add(new Line(new XYZ(i * 2, i, 0), new XYZ(60 + i, 20 + i * 2, 0)));
        }
      }

      const outPath = path.join(outDir, `complex_${ACadVersion[version]}.dwg`);
      writeDocumentToFile(doc, outPath);

      expect(fs.existsSync(outPath)).toBe(true);
      expect(fs.statSync(outPath).size).toBeGreaterThan(0);

      const readBack = new DwgReader(readFileAsArrayBuffer(outPath));
      const parsed = readBack.read();
      expect(parsed).not.toBeNull();
      expect(parsed.blockRecords).not.toBeNull();
      expect(parsed.layers).not.toBeNull();
      expect(parsed.lineTypes).not.toBeNull();
    }
  });
});
